name: Test and Build OpenSearch Querqy Plugin

on: [pull_request, push]

env:
  OPENSEARCH_VERSION: '2.2.1'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Gradle
        run: |
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Create Artifact Path
        run: |
          mkdir -p opensearch-querqy-builds
          cp -r ./build/distributions/*.zip opensearch-querqy-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-querqy
          path: opensearch-querqy-builds
